Added integration test

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -206,12 +206,16 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-      - name: "Run Integration Tests"
-        working-directory: hello-world
-        shell: bash
-        run: npm ci && npm run test
-
-          # trigger the integration tests here
+      - run: |
+        .github/scripts/fetchenv.sh ${TESTING_STACK_NAME} ${TESTING_REGION} > .env;
+        source .env;
+        if curl $HelloWorldApi | grep "hello world"; then
+          echo "'hello world' found in curl response :)"
+          exit 0
+        else
+          echo "'hello world' not found in curl response :("
+          exit 1
+        fi
 
   deploy-prod:
     if: github.ref == 'refs/heads/main'
